---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates for ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  tasks:

  - name: install apache on web servers
    tags: apache,ubuntu
    ansible.builtin.apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
    when: ansible_distribution == "Ubuntu"

- hosts: fedora
  become: true
  tasks:
  - name: install maria db on fedora
    tags: db,fedora
    ansible.builtin.dnf:
      name: "{{ mariadb }}"
      state: latest
    when: ansible_distribution == "Fedora"
