---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates for ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  tasks:

  - name: create_user
    tags: always
    ansible.builtin.user:
      name: simone
      groups: root

  - name: install apache on web servers
    tags: apache,ubuntu
    ansible.builtin.apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
    when: ansible_distribution == "Ubuntu"

  - name: install apache on fedora
    tags: apache,fedora
    ansible.builtin.dnf:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: change email address for admin
    tags: apache,fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin mahmoudnasser1561@gmail.com
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: Deploy static site to Apache document root
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: files/
      dest: /var/www/html/
      owner: mahmoud
      group: mahmoud
      mode: "0644"
      directory_mode: "0755"
    when: ansible_distribution == "Ubuntu"


- hosts: fedora
  become: true
  tasks:
  - name: install maria db on fedora
    tags: db,fedora
    ansible.builtin.dnf:
      name: "{{ mariadb }}"
      state: latest
    when: ansible_distribution == "Fedora"
