- name: install apache on web servers (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - "{{ apache_package }}"
  when: ansible_distribution == "Ubuntu"

- name: install apache on web servers (Fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    name: "{{ apache_package }}"
  when: ansible_distribution == "Fedora"

- name: ensure apache is running (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.service:
    name: "{{ apache_package }}"
    state: started
  when: ansible_distribution == "Ubuntu"

- name: change email address for admin
  tags: apache, "Fedora"
  ansible.builtin.lineinfile:
    path: /etc/httpd?conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin mahmoudnasser1561@gmail.com
  when: ansible_distribution == "Fedora"
  notify: restart_apache

